name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run gradle tests
      run: |
        cd rollerball
        gradle test
    - name: Connect to mysql server
      run: mysql --user=root --password root -e 'SHOW TABLES ;'
